# cloudbuild.yaml
# This file explicitly tells Google Cloud Build how to deploy your App Engine app.

steps:
- name: 'gcr.io/cloud-builders/gcloud'
  # The 'gcloud app deploy' command will read your app.yaml,
  # install dependencies from requirements.txt, and deploy your app.
  # It takes care of finding the Python runtime specified in app.yaml.
  args: ['app', 'deploy', '--project', '${PROJECT_ID}', '--quiet']
  # '--project', '${PROJECT_ID}' ensures it deploys to the correct project.
  # '${PROJECT_ID}' is an automatic variable provided by Cloud Build.
  # '--quiet' prevents interactive prompts during deployment.
